name: EntersPlots
author: Enter Dimension
version: 1.1.0
description: A plugin produced privately for some person called tuff.
main: me.enterdimension.entersplots.main
commands:
    plots:
        description: Allows claiming, selling and editing access of plots.
        usage: |
            ยง6/plots help:ยงr Displays all commands for Enter's Plot Plugin.
permissions:
    plots.*:
        description: Grants access to all Enter's Plots commands.
        children:
            plots.control: true
            plots.admin: true
            plots.name: true
            plots.password: true
            plots.override: true
    plots.control:
        description: Allows claiming, selling and basic management of plots.
        default: true
    plots.admin:
        description: Allows advanced control and some extra features for plots.
        default: op
    plots.name:
        description: Allows naming of owned plots.
        default: true
    plots.password:
        description: Allows unlocking a locked plot with a password.
        default: op
    plots.override:
        description: Allows bypassing any protection on any plot.