name: EntersPlots
author: Enter Dimension
version: 1.1.0
description: A plugin produced privately for some person called tuff.
main: me.enterdimension.entersplots.main
commands:
    plots:
        description: Allows claiming, selling and editing access of plots.
        usage: |
            ยง6/plots help:ยงr Displays all commands for Enter's Plot Plugin.